name: miswag_auth
description: A drop-in authentication and session flow management plugin.
version: 0.1.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.3
  shared_preferences: ^2.2.2
  dio: ^5.4.2+1
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
