# This workflow used to block the merge of pull requests that contain hardcoded secrets.
# It runs TruffleHog to scan for secrets in the PR commits and block the merge if any found.
# https://trufflesecurity.com/trufflehog

name: TruffleHog PR - CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  call-trufflehog-scan:
    uses: Miswag/SaC/.github/workflows/trufflehog-scan.yml@main
    with:
      base: ${{ github.event.repository.default_branch }}
      head: HEAD
